### PR TITLE
Corrected typehinting for all()-method

### PR DESCRIPTION
**Pull request by ddewit**
Minor typo/structure mix-up corrected.

### CODE REVIEW

**Comment by ddewit** [comment]
@bjornpost, any interest in getting these pulled so I can set composer to use your repo instead of my own patch-1? :)

**Comment by bjornpost** [comment]
Hi Danny, sorry, didn't notice the pull request. I'll have a look at them tonight and pull them in. As you might have noticed this is very much a work in progress, things will be rough around the edges :-).

**Comment by ddewit** [comment]
Cool. It's fine being rough, just needs some more thorough testing and real use, that's all ;).

**Comment by bjornpost** [comment]
Thanks, merged!

**Pull request merged**
